name: story_app
description: 'Story App'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.2 <=4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  http: ^1.3.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  sqflite: ^2.4.1
  timezone: ^0.10.0
  uuid: ^4.5.1
  app_settings: ^5.2.0
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  country_flags: ^3.2.0
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  flutter_image_compress: ^2.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/roboto_slab/RobotoSlab-Black.ttf
          weight: 700
        - asset: assets/fonts/roboto_slab/RobotoSlab-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_slab/RobotoSlab-Bold.ttf
          weight: 500
        - asset: assets/fonts/roboto_slab/RobotoSlab-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/roboto_slab/RobotoSlab-Medium.ttf
          weight: 300
        - asset: assets/fonts/roboto_slab/RobotoSlab-Regular.ttf
          weight: 200
        - asset: assets/fonts/roboto_slab/RobotoSlab-Light.ttf
          weight: 100
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 100
