// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__3tUbaiAU1_q3KrQXXWm5Br-gTl8f6U',
    appId: '1:502903425301:web:678b3b16db5b52491ec11c',
    messagingSenderId: '502903425301',
    projectId: 'storyapp-be175',
    authDomain: 'storyapp-be175.firebaseapp.com',
    storageBucket: 'storyapp-be175.firebasestorage.app',
    measurementId: 'G-904BTCNKJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpOgsCpCMIB-WOgc8bsL6W7tE8FGoSh5c',
    appId: '1:502903425301:android:5b5ef8e93dfc7e8b1ec11c',
    messagingSenderId: '502903425301',
    projectId: 'storyapp-be175',
    storageBucket: 'storyapp-be175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD--JVldpXOAExyS7MSQazsvTedpufvKM4',
    appId: '1:502903425301:ios:e7e816efe9d26c5a1ec11c',
    messagingSenderId: '502903425301',
    projectId: 'storyapp-be175',
    storageBucket: 'storyapp-be175.firebasestorage.app',
    iosBundleId: 'com.example.storyApp',
  );
}
